# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: USMB.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='USMB.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nUSMB.proto\"0\n\x12InscriptionRequest\x12\r\n\x05\x61nnee\x18\x01 \x01(\x05\x12\x0b\n\x03nom\x18\x02 \x01(\t\"&\n\x13InscriptionResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2K\n\x0bInscription\x12<\n\x0fInscriptionUSMB\x12\x13.InscriptionRequest\x1a\x14.InscriptionResponseb\x06proto3'
)




_INSCRIPTIONREQUEST = _descriptor.Descriptor(
  name='InscriptionRequest',
  full_name='InscriptionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='annee', full_name='InscriptionRequest.annee', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nom', full_name='InscriptionRequest.nom', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=62,
)


_INSCRIPTIONRESPONSE = _descriptor.Descriptor(
  name='InscriptionResponse',
  full_name='InscriptionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='InscriptionResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['InscriptionRequest'] = _INSCRIPTIONREQUEST
DESCRIPTOR.message_types_by_name['InscriptionResponse'] = _INSCRIPTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InscriptionRequest = _reflection.GeneratedProtocolMessageType('InscriptionRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSCRIPTIONREQUEST,
  '__module__' : 'USMB_pb2'
  # @@protoc_insertion_point(class_scope:InscriptionRequest)
  })
_sym_db.RegisterMessage(InscriptionRequest)

InscriptionResponse = _reflection.GeneratedProtocolMessageType('InscriptionResponse', (_message.Message,), {
  'DESCRIPTOR' : _INSCRIPTIONRESPONSE,
  '__module__' : 'USMB_pb2'
  # @@protoc_insertion_point(class_scope:InscriptionResponse)
  })
_sym_db.RegisterMessage(InscriptionResponse)



_INSCRIPTION = _descriptor.ServiceDescriptor(
  name='Inscription',
  full_name='Inscription',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=104,
  serialized_end=179,
  methods=[
  _descriptor.MethodDescriptor(
    name='InscriptionUSMB',
    full_name='Inscription.InscriptionUSMB',
    index=0,
    containing_service=None,
    input_type=_INSCRIPTIONREQUEST,
    output_type=_INSCRIPTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INSCRIPTION)

DESCRIPTOR.services_by_name['Inscription'] = _INSCRIPTION

# @@protoc_insertion_point(module_scope)
