# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import USMB_pb2 as USMB__pb2


class InscriptionStub(object):
    """On définit un service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InscriptionUSMB = channel.unary_unary(
                '/Inscription/InscriptionUSMB',
                request_serializer=USMB__pb2.InscriptionRequest.SerializeToString,
                response_deserializer=USMB__pb2.InscriptionResponse.FromString,
                )


class InscriptionServicer(object):
    """On définit un service
    """

    def InscriptionUSMB(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InscriptionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InscriptionUSMB': grpc.unary_unary_rpc_method_handler(
                    servicer.InscriptionUSMB,
                    request_deserializer=USMB__pb2.InscriptionRequest.FromString,
                    response_serializer=USMB__pb2.InscriptionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Inscription', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Inscription(object):
    """On définit un service
    """

    @staticmethod
    def InscriptionUSMB(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Inscription/InscriptionUSMB',
            USMB__pb2.InscriptionRequest.SerializeToString,
            USMB__pb2.InscriptionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
